# Generated by Django 5.2.7 on 2025-12-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('iconita', models.CharField(blank=True, help_text='Ex: 🍕 🍝 🥤 🍰', max_length=10)),
                ('ordine', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('finalizata', models.BooleanField(default=False)),
                ('observatii', models.TextField(blank=True)),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.masa')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponibil', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produse', to='demo.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ImagineProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='produse/')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='demo.produs')),
            ],
        ),
        migrations.CreateModel(
            name='ProdusComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField()),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozitii', to='demo.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.produs')),
            ],
        ),
    ]
