# Generated by Django 5.2.7 on 2025-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='ingrediente',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='produs',
            name='valori_nutritionale',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
