# Generated by Django 5.2.7 on 2025-12-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_produs_ingrediente_produs_valori_nutritionale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.masa')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.produs')),
            ],
            options={
                'unique_together': {('masa', 'produs')},
            },
        ),
    ]
